/* ===== ORDER SYNC SETTINGS =====
   Paste your Google Apps Script "Web app URL" between the quotes (see SETUP steps). */
window.AA_API='';
/* ================================ */
/* [id, name, price (PHP), unit, description, search alias] — photo = assets/products/<id>.jpg */
window.AA_PRODUCTS={
veg:[
["upo","Upo",50,"kg","Simple, fresh & delicious!","bottle gourd"],
["talong","Talong",50,"kg","Grill it, fry it or cook it your way!","eggplant"],
["sitaw","Sitaw",30,"bundle","Crisp, fresh & budget-friendly!","string beans"],
["onion","Onion",70,"kg","The flavor your dishes need!","sibuyas"],
["sayote","Sayote",40,"kg","Fresh, crisp & easy to cook!","chayote"],
["saluyot","Saluyot",30,"bundle","Fresh greens for healthy meals!","jute"],
["cabbage","Cabbage",60,"kg","Crisp, fresh & family-approved!","repolyo"],
["petchay","Petchay",25,"bundle","Fresh greens, great taste!","bok choy"],
["potato","Patatas",70,"kg","A kitchen favorite for every meal!","potato"],
["mustasa","Mustasa",40,"bundle","Fresh greens with a flavorful kick!","mustard"],
["ginger","Luya",40,"kg","Fresh aroma, better flavor!","ginger"],
["kundol","Kundol",60,"kg","Fresh and perfect for hearty dishes!","winter melon"],
["kangkong","Kangkong",45,"bundle","Fresh, crisp & delicious!","water spinach"],
["tomato","Tomato",50,"kg","Juicy, fresh & full of flavor!","kamatis"],
["squash","Kalabasa",50,"kg","Naturally sweet & perfect for family meals!","squash"],
["carrots","Carrots",50,"kg","Crunchy, colorful & delicious!","karot"],
["bawang","Bawang",70,"kg","Small but mighty in flavor!","garlic"],
["ampalaya","Ampalaya",50,"kg","Fresh, flavorful & nutritious!","bitter melon"],
["sililabuyo","Sili Labuyo",400,"kg","Spice up your meals!","chili"],
["siligreen","Sili Green",200,"kg","Fresh, crisp & flavorful!","haba chili"],
["okra","Okra",100,"kg","Fresh goodness in every bite!",""],
["pipino","Pipino",130,"kg","Cool, crisp & refreshing!","cucumber"],
["labanos","Labanos",150,"kg","Crunchy, fresh & delicious!","radish"],
["bataw","Bataw",130,"kg","Fresh and perfect for your favorite dishes!","hyacinth bean"],
["patani","Patani",110,"kg","Fresh, tasty & nutritious!","lima bean"],
["sigarilyas","Sigarilyas",130,"kg","Crispy freshness for every meal!","winged bean"],
["patola","Patola",90,"kg","Tender, fresh & perfect for soup!","sponge gourd"]],
fruit:[
["guava","Guava",60,"kg","Sweet, crunchy, and packed with vitamin C. A farm-fresh everyday favorite.","bayabas"],
["santol","Santol",100,"kg","Tangy-sweet with a soft, cottony pulp. A classic taste of the countryside.",""],
["banana","Banana",90,"kg","Naturally sweet and energy-boosting. The perfect snack any time of day.","saging"],
["papaya","Papaya",80,"kg","Soft, juicy, and gentle on the tummy. Great for breakfast or dessert.",""],
["mango","Mango",220,"kg","Golden, honey-sweet, and irresistibly juicy. The king of tropical fruits.","mangga"],
["watermelon","Watermelon",60,"kg","Cool, crisp, and refreshing. Your best partner against the summer heat.","pakwan"],
["pineapple","Pineapple",120,"kg","Sweet and tangy with a tropical burst of flavor. Perfect fresh or in juice.","pinya"],
["rambutan","Rambutan",80,"kg","Hairy outside, sweet and juicy inside. Peel, pop, and enjoy!",""],
["coconut","Coconut",40,"piece","Refreshing water and creamy meat in one. Nature's own drink.","niyog buko"],
["dragonfruit","Dragon Fruit",150,"kg","Mildly sweet, vibrant, and full of fiber. As healthy as it is beautiful.",""],
["pomelo","Pomelo",80,"kg","Large, juicy segments with a sweet-tart zing. Light and refreshing.","suha"],
["kiwi","Kiwi",100,"kg","Tangy-sweet and rich in vitamin C. A small fruit with a big boost.",""],
["grapes","Grapes",150,"kg","Plump, sweet, and ready to snack on. Perfect for sharing.","ubas"],
["apple","Apple",100,"kg","Crisp, juicy, and satisfying. A healthy bite for the whole family.","mansanas"],
["lansones","Lansones",150,"kg","Sweet-sour and delightfully juicy. A seasonal treat worth the wait.","lanzones"],
["corn","Corn",100,"kg","Sweet, tender kernels fresh from the farm. Great boiled, grilled, or in soups.","mais"],
["mangosteen","Mangosteen",200,"kg","Soft, sweet, and slightly tangy. Called the \"queen of fruits\" for a reason.",""],
["strawberry","Strawberry",150,"kg","Bright, sweet, and fragrant. Perfect for desserts, shakes, or snacking.",""],
["calamansi","Calamansi",100,"kg","Small but packed with citrusy zing. Ideal for juices, dips, and marinades.","kalamansi"],
["lemon","Lemon",300,"kg","Bold, zesty, and fresh. Brightens drinks, dishes, and desserts.",""],
["avocado","Avocado",150,"kg","Creamy, rich, and full of healthy fats. Delicious in shakes, toast, and salads.",""],
["melon","Melon",90,"kg","Sweet, soft, and super refreshing. A light treat for any occasion.","cantaloupe"],
["longan","Longan",150,"kg","Delicate, sweet, and juicy. Little bites of tropical goodness.",""],
["pear","Pear",120,"kg","Soft, sweet, and gently crisp. A smooth, refreshing snack.",""],
["orange","Orange",100,"kg","Juicy, sweet, and full of vitamin C. Peel it or squeeze it fresh!","dalandan"]]};
